// AUTO-GENERATED by astro-cms — do not edit manually

export interface Post {
  id: number
  title: string
  content: string | null
  status: 'draft' | 'published' | null
  image: { key: string; url: string } | null
  createdAt: string
  updatedAt: string
}
